USE ROLE ACCOUNTADMIN;
CREATE CORTEX SEARCH SERVICE IF NOT EXISTS GQH.CONTEXT.SEARCH
 ON BODY ATTRIBUTES SOURCE_PATH, DOC_SHA
 WAREHOUSE=GQH_WH TARGET_LAG='1 hour' AUTO_SUSPEND=1800
 AS SELECT BODY, SOURCE_PATH, DOC_SHA, START_LINE, END_LINE FROM GQH.CONTEXT.PASSAGES;
GRANT USAGE ON CORTEX SEARCH SERVICE GQH.CONTEXT.SEARCH TO ROLE GQH_RESEARCHER;
