USE ROLE ACCOUNTADMIN;
ALTER TABLE GQH.RAW.FILES SET CHANGE_TRACKING=TRUE;
CREATE CORTEX SEARCH SERVICE IF NOT EXISTS GQH.CONTEXT.SEARCH
 ON BODY ATTRIBUTES SOURCE_PATH, DOC_SHA
 WAREHOUSE=GQH_WH TARGET_LAG='1 hour' AUTO_SUSPEND=1800
 AS SELECT p.BODY, p.SOURCE_PATH, p.DOC_SHA, p.START_LINE, p.END_LINE
 FROM GQH.CONTEXT.PASSAGES p JOIN (
   SELECT SOURCE_PATH,SHA256 FROM GQH.RAW.FILES
   WHERE COLLECTION='context' AND LOADED=TRUE AND SOURCE_PATH<>'@manifest' AND SOURCE_PATH NOT LIKE '%/original/%'
   QUALIFY ROW_NUMBER() OVER (PARTITION BY SOURCE_PATH ORDER BY IMPORTED_AT DESC)=1
 ) f ON f.SOURCE_PATH=p.SOURCE_PATH AND f.SHA256=p.DOC_SHA;
GRANT USAGE ON CORTEX SEARCH SERVICE GQH.CONTEXT.SEARCH TO ROLE GQH_RESEARCHER;
