"""Finite book-derived signal registry; expansion and execution belong to runner."""

from . import cross_sectional as cross
from . import futures, learning, technical
from .base import ROOTS, StrategySpec

CONTROLS = {
    "separated_triple_ma": "same-universe unfiltered 5/20/60 triple-MA baseline",
    "trend": "equal-risk long portfolio and fixed 120-bar trend",
    "reversal": "equal-risk long portfolio and zero-return cash",
    "carry": "equal-risk CL/GC long portfolio",
    "volume_reversal": "same-universe unfiltered five-bar reversal",
    "single_ma": "same-universe fixed 120-bar trend",
    "double_ma": "same-universe single-MA baseline",
    "triple_ma": "same-universe double-MA baseline",
    "channel": "same-universe unfiltered reversal",
    "pivot": "same-universe unfiltered reversal",
    "ibs": "same-universe unfiltered reversal",
    "price_momentum": "same-universe time-series trend and equal-risk long",
    "low_volatility": "same-universe equal-risk long and volatility-matched control",
    "pair_reversal": "ES/NQ passive equal-risk and unfiltered pair reversal",
    "rotation": "same-universe equal-risk long and fixed trend",
    "rotation_ma": "same-universe unfiltered relative rotation",
    "dual_rotation": "same-universe unfiltered rotation and GC fallback control",
    "skewness": "CL/GC long and unfiltered carry",
    "knn": "same-universe fixed trend and reversal",
    "hp_ma": "same-universe unfiltered 10/30-bar moving averages",
    "commodity_long": "zero-return cash; exposure control, not selectable alpha",
}


def spec(
    id,
    sections,
    pages,
    mechanism,
    inputs,
    grid,
    signal,
    adaptation,
    min_roots=1,
    supported_roots=ROOTS,
):
    def checked(view, params):
        metadata = STRATEGIES[id]
        metadata.validate_params(params)
        metadata.validate_universe(view.roots)
        if view.information_asof >= view.decision_at:
            raise ValueError("Information cutoff must precede executable decision")
        result = signal(view, params)
        if tuple(result.index) != tuple(view.roots):
            raise ValueError("Signal must match configured root order")
        return result

    return StrategySpec(
        id=id,
        book_sections=tuple(sections),
        printed_pages=tuple(pages),
        mechanism=mechanism,
        required_inputs=tuple(inputs),
        default_grid=tuple(grid),
        signal=checked,
        adaptation=adaptation,
        min_roots=min_roots,
        supported_roots=tuple(supported_roots),
        null=f"No positive net incremental return against {CONTROLS[id]}.",
        falsifier=f"Reject if paired excess against {CONTROLS[id]} fails uncertainty, doubled costs or neighbouring parameters.",
    )


_ITEMS = [
    spec(
        "separated_triple_ma",
        ["3.13"],
        [51],
        "Persistent demand may produce trend separation exceeding ordinary daily noise.",
        ["ohlc", "positions"],
        [{"lengths": (5, 20, 60), "cutoff": x} for x in (0.25, 0.5, 1.0)],
        technical.separated_triple_ma,
        "Research extension: new entries require fast/medium separation exceeding cutoff times trailing 20-day point-change volatility; existing exit rule unchanged.",
    ),
    spec(
        "trend",
        ["10.4"],
        [96],
        "Slow investor information adjustment may prolong price trends.",
        ["point_changes"],
        [{"lookback": n} for n in (60, 120, 240)],
        futures.trend,
        "Sign of same-contract point-change sum; engine applies common volatility risk policy.",
    ),
    spec(
        "reversal",
        ["10.3"],
        [95],
        "Temporary inventory pressure may reverse after short-lived trades.",
        ["point_changes"],
        [{"lookback": n} for n in (5, 10, 20)],
        futures.reversal,
        "Normalise point changes by 63-bar volatility before demean; six heterogeneous risk units.",
        2,
    ),
    spec(
        "carry",
        ["9.1"],
        [89],
        "Inventory and hedging demand may price commodity curve risk.",
        ["curve"],
        [{}],
        futures.carry,
        "Annualised near/far slope, demean CL/GC; trade eligible outright, not free roll gaps.",
        2,
        ("CL", "GC"),
    ),
    spec(
        "volume_reversal",
        ["10.3.1"],
        [95],
        "Unusual traded volume may mark temporary overreaction.",
        ["point_changes", "whole_root_volume"],
        [{"cutoff": x} for x in (1.0, 1.5, 2.0)],
        futures.volume_reversal,
        "Volume-only adaptation: frozen five-bar base, no unavailable open-interest filter.",
        2,
    ),
    spec(
        "single_ma",
        ["3.11", "4.6"],
        [49, 65],
        "Slow price adjustment may sustain a directional trend.",
        ["ohlc"],
        [{"lengths": (n,)} for n in (20, 60, 120)],
        technical.moving_average,
        "Fixed dated-contract price vs strictly previous-bar SMA; common futures risk policy.",
    ),
    spec(
        "double_ma",
        ["3.12"],
        [50],
        "Fast and slow price trends may identify persistent demand.",
        ["ohlc"],
        [{"lengths": x} for x in ((5, 20), (10, 40), (20, 80))],
        technical.moving_average,
        "Ordered finite SMA pairs on one dated instrument; no added stop rule.",
    ),
    spec(
        "triple_ma",
        ["3.13"],
        [51],
        "Agreement across trend horizons may reduce false entries.",
        ["ohlc", "positions"],
        [{"lengths": x} for x in ((3, 10, 21), (5, 20, 60), (10, 40, 120))],
        technical.moving_average,
        "Book ordered triple entries and fast/medium exits, using actual held position sign.",
    ),
    spec(
        "channel",
        ["3.15"],
        [52],
        "Price excursions to channel bounds may reflect temporary pressure.",
        ["ohlc", "positions"],
        [{"lookback": n} for n in (10, 20, 60)],
        technical.channel,
        "Contrarian close-channel floor/ceiling rule; prior channel excludes signal bar; no intraday fills.",
    ),
    spec(
        "pivot",
        ["3.14"],
        [51],
        "Prior traded range may anchor participant support/resistance.",
        ["ohlc"],
        [{}],
        technical.pivot,
        "Daily closed-bar snapshot of book pivot entry/exit zones, next executable open only.",
    ),
    spec(
        "ibs",
        ["4.4"],
        [64],
        "Close location within the traded range may mark temporary imbalance.",
        ["ohlc"],
        [{}],
        technical.ibs,
        "Long lowest/short highest IBS; one per side replaces infeasible six-root deciles.",
        2,
    ),
    spec(
        "price_momentum",
        ["3.1"],
        [40],
        "Delayed information diffusion may preserve relative winners.",
        ["notional_returns"],
        [{"lookback": n, "skip": 21} for n in (63, 126, 252)],
        cross.momentum,
        "Sum causal notional P&L returns, skip21 bars; one winner/loser instead of stock deciles.",
        2,
    ),
    spec(
        "low_volatility",
        ["3.4"],
        [42],
        "Leverage constraints may bid up high-volatility exposures.",
        ["notional_returns"],
        [{"lookback": n} for n in (63, 126, 252)],
        cross.low_volatility,
        "Rank comparable notional-return volatility; engine risk allocation may attenuate anomaly.",
        2,
    ),
    spec(
        "pair_reversal",
        ["3.8", "3.9"],
        [45, 46],
        "Related equity-index demand may temporarily diverge.",
        ["notional_returns"],
        [{"lookback": n, "pair": ("ES", "NQ")} for n in (1, 5, 10)],
        cross.pair_reversal,
        "Fixed ES/NQ pair; require63-bar historical correlation>=0.5; no discovered pair selection.",
        2,
        ("ES", "NQ"),
    ),
    spec(
        "rotation",
        ["4.1"],
        [61],
        "Persistent relative demand may favour winning asset exposure.",
        ["notional_returns"],
        [{"lookback": n, "filter": "none"} for n in (63, 126, 252)],
        cross.rotation,
        "Long highest six-futures notional-return sum; not literal sector ETF universe.",
        2,
    ),
    spec(
        "rotation_ma",
        ["4.1.1"],
        [62],
        "Absolute trend may filter relative winners in declining markets.",
        ["notional_returns", "ohlc"],
        [{"lookback": n, "filter": "own_ma", "ma": 120} for n in (63, 126, 252)],
        cross.rotation,
        "Highest root admitted only above own prior 120-bar SMA; otherwise cash.",
        2,
    ),
    spec(
        "dual_rotation",
        ["4.1.2"],
        [62],
        "Broad-equity trend may condition risk-on relative demand.",
        ["notional_returns", "ohlc"],
        [{"lookback": n, "filter": "broad_ma", "ma": 120} for n in (63, 126, 252)],
        cross.rotation,
        "ES broad-market proxy; GC fallback is declared, not guaranteed uncorrelated.",
        2,
    ),
    spec(
        "skewness",
        ["9.5"],
        [91],
        "Lottery preference may depress subsequent high-skew commodity returns.",
        ["notional_returns"],
        [{"lookback": n} for n in (63, 126, 252)],
        futures.skewness,
        "Exact book moment statistic; CL/GC opposite ranks replace broad commodity quintiles.",
        2,
        ("CL", "GC"),
    ),
    spec(
        "knn",
        ["3.17"],
        [53],
        "Similar historical price/volume states may precede similar returns.",
        ["ohlc"],
        [{"neighbours": n} for n in (5, 10, 20)],
        learning.knn,
        "Fixed-contract126 matured 5-bar labels; trailing 5/20 price and 5 volume features; train-only min/max scaling.",
    ),
    spec(
        "hp_ma",
        ["8.1"],
        [85],
        "Filtering noisy currency prices may expose persistent trend.",
        ["ohlc"],
        [{"smoothing": n} for n in (1600.0, 6400.0, 25600.0)],
        learning.hp_ma,
        "Purchased 6E futures proxy, trailing 126-bar endpoint HP then 10/30 SMA; daily windows not literal multiyear spot.",
        1,
        ("6E",),
    ),
    spec(
        "commodity_long",
        ["9.3"],
        [90],
        "Commodity exposure may diversify equity and bond risks.",
        [],
        [{}],
        futures.commodity_long,
        "CL/GC long exposure control, not an alpha candidate.",
        2,
        ("CL", "GC"),
    ),
]
STRATEGIES = {item.id: item for item in _ITEMS}


def get_strategy(strategy_id: str) -> StrategySpec:
    try:
        return STRATEGIES[strategy_id]
    except KeyError as error:
        raise ValueError(f"Unknown strategy: {strategy_id}") from error
